### ISSUE TITLE
enable mirroring of neurons / coords 

### ISSUE THREAD

**Issue by jefferis** [jefferislab/bridging_on-the-fly#8]
* Should that be in space of brain of origin?
* should work for same brain (i.e. just mirror, no bridge)

**Comment by ajdm** [comment]
Neurons can be mirrored as of 77915b5eb484e4d11ebd0a6be732103cd62ff97d.

**Comment by ajdm** [comment]
Coordinates can be mirrored as of 5b42f9ea00b1e82adaf72abc5611830387a2fddd.
